### PR TITLE
Universe Class, GameStates and more

### PR DESCRIPTION
**Pull request by IllustrisJack**
- Moves star system generation to its own class (universe class).
- Moves universe economy to its own class.
- Prepare universe & universe economy class which can handle all existing systems.
- Create and use a dynamic game state instead of writing into the static config.
- bunch of fixes for the menu
- Stations will now be placed at a minimum distance to other stations
- Load all enums in one go
- Load all types in one go
- & more

### CODE REVIEW

**Comment by Flatfingers** [comment]
I haven't found what it is yet, but LTheory and TestEcon are crashing on startup.

It looks like it has something to do with calling ./script/GameObjects/Entities/Ship/Ship.lua -- that's where a number of calls are made (to Inventory.lua, Health.lua, etc.) that set some core capabilities for entities. An example of this is the call to `self:addInventory(100)` on line 12 of Ship.lua -- that call has to happen in order for Inventory.lua to perform the `self.inventory = {}` statement.

Without that, the call in System.lua to `ship:setInventoryCapacity(Config.econ.eInventory)` goes to Inventory.lua which tries to `assert(self.inventory)`, which fails because the addInventory() call that is supposed to create that table never happens. (You can comment out the setInventoryCapacity() call and you still get a crash because Health works the same way.)

However, LTheoryRedux does _not_ crash on startup. So it looks like you must be doing something different there with your changes to ./script/Config/App.lua -> GameState.lua than you're doing with LTheory and TestEcon.

Strictly speaking, of course we don't actually have to have LTheory and TestEcon. But they are both really useful for quick testing, and I'd hate to lose them if we don't have to.

I'm continuing testing of LTheoryRedux; just wanted to give you a heads-up on this issue while I'm still reviewing.

**Comment by IllustrisJack** [comment]
> I haven't found what it is yet, but LTheory and TestEcon are crashing on startup.
> 
> It looks like it has something to do with calling ./script/GameObjects/Entities/Ship/Ship.lua -- that's where a number of calls are made (to Inventory.lua, Health.lua, etc.) that set some core capabilities for entities. An example of this is the call to `self:addInventory(100)` on line 12 of Ship.lua -- that call has to happen in order for Inventory.lua to perform the `self.inventory = {}` statement.
> 
> Without that, the call in System.lua to `ship:setInventoryCapacity(Config.econ.eInventory)` goes to Inventory.lua which tries to `assert(self.inventory)`, which fails because the addInventory() call that is supposed to create that table never happens. (You can comment out the setInventoryCapacity() call and you still get a crash because Health works the same way.)
> 
> However, LTheoryRedux does _not_ crash on startup. So it looks like you must be doing something different there with your changes to ./script/Config/App.lua -> GameState.lua than you're doing with LTheory and TestEcon.
> 
> Strictly speaking, of course we don't actually have to have LTheory and TestEcon. But they are both really useful for quick testing, and I'd hate to lose them if we don't have to.
> 
> I'm continuing testing of LTheoryRedux; just wanted to give you a heads-up on this issue while I'm still reviewing.

We should ditch the original LTheory.lua and move forward with Redux. What do you need? The fast/direct startup or something special? I can implement those things to Redux once you give me a list of needed features :)

I´ll check out TestEcon later after I wake up. Don't think the issue is too hard to find.

Thanks for the ongoing review! :D

**Comment by Flatfingers** [comment]
Noticed that writing of values to user.ini was overwriting them with the default values from the Config.X.Y definitions in App.lua. It looks like `./script/Systems/Files/InitFiles.lua` didn't get updated to convert from the old Config.X.Y format to the new GameState.X.Y redefinitions.

Some of this confusion is caused by trying to retain the old Config.X.Y definitions: in GameState.lua, you're doing things like:

```
GameState.ui = {
  showTrackers          = Config.ui.showTrackers,
```

I can see this is a quick way to get the new GameState approach working, but leaving the old Config.X.Y values existing means it's easy to write to the old definitions. When that happens, the game won't break, but it'll never use updated values in the new GameState.X.Y structure. This is confusing. At some point (maybe not immediately, up to you) I'd say let's nuke the Config.X.Y values so we know for sure that only the new GameState.X.Y values are being used anywhere.

Related note: at this point we could probably remove ./script/Config/Local.lua entirely. (You'll notice it also wasn't updated to use the new GameState.X.Y values -- this is yet another reason to explicitly remove any variable definition in Config.lua for which you've created a new version in GameState.lua.

**Comment by Flatfingers** [comment]
> We should ditch the original LTheory.lua and move forward with Redux. What do you need? The fast/direct startup or something special? I can implement those things to Redux once you give me a list of needed features :)

I'd really rather not lose LTheory.lua unless we have to. (And whatever's breaking it should be fixed by whatever fix you apply to TestEcon.lua.) LTheory has the very nice feature of letting us test Flight mode changes (e.g., HUD) super-quickly because we don't have to wait for the Main Menu to come up and do all that clickety-click. If it's as easy to restore LTheory as it is to restore TestEcon, I'd strongly prefer we not nuke it just yet. That time may come eventually, of course.

**Comment by IllustrisJack** [comment]
> Noticed that writing of values to user.ini was overwriting them with the default values from the Config.X.Y definitions in App.lua. It looks like `./script/Systems/Files/InitFiles.lua` didn't get updated to convert from the old Config.X.Y format to the new GameState.X.Y redefinitions.
> 
> Some of this confusion is caused by trying to retain the old Config.X.Y definitions: in GameState.lua, you're doing things like:
> 
> ```
> GameState.ui = {
>   showTrackers          = Config.ui.showTrackers,
> ```
> 
> I can see this is a quick way to get the new GameState approach working, but leaving the old Config.X.Y values existing means it's easy to write to the old definitions. When that happens, the game won't break, but it'll never use updated values in the new GameState.X.Y structure. This is confusing. At some point (maybe not immediately, up to you) I'd say let's nuke the Config.X.Y values so we know for sure that only the new GameState.X.Y values are being used anywhere.
> 
> Related note: at this point we could probably remove ./script/Config/Local.lua entirely. (You'll notice it also wasn't updated to use the new GameState.X.Y values -- this is yet another reason to explicitly remove any variable definition in Config.lua for which you've created a new version in GameState.lua.

The GameState is to differentiate between dynamic and static values. Meaning that values that should be static or are static on launch e.g. from config file so they can be reset to if needed. Dynamic changes should only be made in GameState and I tested the config.ini and it was still working. Maybe I missed some values?

**Comment by Flatfingers** [comment]
> Maybe I missed some values?

fullscreen, hudStyle, and cursorStyle in InitFiles.lua

**Comment by IllustrisJack** [comment]
> > We should ditch the original LTheory.lua and move forward with Redux. What do you need? The fast/direct startup or something special? I can implement those things to Redux once you give me a list of needed features :)
> 
> I'd really rather not lose LTheory.lua unless we have to. (And whatever's breaking it should be fixed by whatever fix you apply to TestEcon.lua.) LTheory has the very nice feature of letting us test Flight mode changes (e.g., HUD) super-quickly because we don't have to wait for the Main Menu to come up and do all that clickety-click. If it's as easy to restore LTheory as it is to restore TestEcon, I'd strongly prefer we not nuke it just yet. That time may come eventually, of course.

Rather do it now. I can implement a quick start script instead.

**Comment by Flatfingers** [comment]
> fullscreen, hudStyle, and cursorStyle in InitFiles.lua

humanPlayerShipName as well

**Comment by IllustrisJack** [comment]
> > Maybe I missed some values?
> 
> fullscreen, hudStyle, and cursorStyle in InitFiles.lua

ahhh yeah those were added in one of the merges :D - I knew there were some things left

**Comment by Flatfingers** [comment]
> ahhh yeah those were added in one of the merges :D - I knew there were some things left

Looks like fullscreen is actually OK. (I was looking at a different version of InitFiles.lua.)

**Comment by Flatfingers** [comment]
Line 553 in your MainMenu.lua got changed to:

    if HmGui.Button("+") and guiSettings[11][1] < Config.gen.nEconNPCs then

from:

    if HmGui.Button("+") and guiSettings[11][1] < 100 then

The other upper bounds for "sliders" in the Settings screen are still using the hardcoded limits I gave them. Obviously we can fiddle with those numbers, but for now let's set this back to 100. If you want to try to keep distinguishing between static and dynamic values, that would be better in a later update so we can get this big boy approved.

**Comment by Flatfingers** [comment]
The change you made to prevent Stations from being too close to each other has caused them to be placed far beyond the 200 "km" limit I imposed on objects in the current "tiny" star system. This limit is a hack, but without it, NPC ships will start to suffer from the "jitter" problem.

**Comment by Flatfingers** [comment]
In Settings, I tried changing the values for the numbers of Economic ships generated, and the number of Escort ships generated. But I found that neither of these did anything now.

When I look at the new Universe code, I see that you've changed the number of economic ships to:

local aiAssetCount = rng:getInt(10, Config.gen.nEconNPCs)

and deleted the escort ships functionality entirely.

I understand reorganizing features, but if you think there's some reason to remove functionality, let's discuss that beforehand, please.

**Comment by Flatfingers** [comment]
When I click on Settings before starting a new game (i.e., in the Main Menu clicking on Load Game or New Game and then using a Random or selected seed), Flight Mode comes up with the Flight Mode game control dialog displayed and the cursor invisible. When I take down the dialog box, then bring it back up and select Exit to Main Menu, the Main Menu comes up with the cursor invisible.

**Comment by Flatfingers** [comment]
I need to stop reviewing again for a bit, but here's what I've found so far:

1.
Change Config.gen.nFields to GameState.gen.nFields in:
  MainMenu.lua
  Universe.lua

Change Config.gen.nEconNPCs to GameState.gen.nEconNPCs in:
  MainMenu.lua
  UniverseEconomy.lua
  System.lua

(The other .gen. values need to be updated in these same ways. I'd identify them all, but I've run out of time for now.)

2. Please change the value "enabled" (as in Config.audio.enabled) to "soundEnabled" so that we can find this value specifically when searching code files. ("enabled" by itself gets used locally by several functions with different meanings.)

3. There's some kind of confusion going on now between GameState.audio.enabled and GameState.audio.musicVolume that is causing the "do not play audio" preference in user.ini to not be respected when the game starts up. I can set these values to "false" in user.ini, but when the game starts the music plays anyway. Somewhere "musicVolume" is being read/used where "enabled" should be, or vice versa.

4. After using Settings in the Main Menu, switching to Flight Mode is still starting up with the flight mode dialog box enabled (with invisible main game cursor).

**Comment by IllustrisJack** [comment]
> 

Some stuff already done + working on a table imp for the config file so everything is done automatic

**Comment by Flatfingers** [comment]
Downloading now for another testing run.

**Comment by Flatfingers** [comment]
Now LTheory and TestEcon run, but LTheoryRedux crashes on startup -- looks like something in InitFiles.lua:

./script/Systems\Files\InitFiles.lua:85: Can't find key in gamestate cat audio for var: enabled with value true

**Comment by IllustrisJack** [comment]
> Now LTheory and TestEcon run, but LTheoryRedux crashes on startup -- looks like something in InitFiles.lua:
> 
> ./script/Systems\Files\InitFiles.lua:85: Can't find key in gamestate cat audio for var: enabled with value true

delete your config file and regen it, i switched to a table driven process

**Comment by Flatfingers** [comment]
OK, variable saving to user.ini is looking good, and reading values from there is looking good. And popping up the Flight mode game controls when going there from Main Menu has been solved.

Remaining items:

1. Occasionally some stations are still being spawned far away from the origin. One very quick look suggests these might be Solar Energy stations, which are a special type that are always generated to insure that factories will always have Energy for production runs. This isn't a big deal, and I'm OK with approving it now and fixing it later. I mention it in case you want to have a quick look at it while investigating the more important comments below.

2. In both LTheory and LTheoryRedux, pressing the "H" key to accelerate time causes a crash:

./script/States\Application.lua:181: attempt to perform arithmetic on local 'timeScale' (a nil value)

3. When in Flight mode, press Esc to bring up the game control dialog, then click on "Load Game". The seed selection screen pops up briefly but gets replaced by the game control dialog. If you then click on "Return to Game" in the game control dialog, the Seed selection dialog is displayed.

4. One very minor thing: I've noticed that when you add a single quote mark in a line of code (usually in a comment), it seems to be adding it as a special character followed by a slanted ("smart") single quote, rather than as the default "straight" single quote character. It's not hurting any of the code, but it is a bit outside the minimal coding standards for the game code. (I know you've asked about coding standards; please consider "straight single-quote characters only" one of those standards. :D )

Overall, this is now _very_ close to being ready for full approval.

**Comment by IllustrisJack** [comment]
> OK, variable saving to user.ini is looking good, and reading values from there is looking good. And popping up the Flight mode game controls when going there from Main Menu has been solved.
> 
> Remaining items:
> 
>     1. Occasionally some stations are still being spawned far away from the origin. One very quick look suggests these might be Solar Energy stations, which are a special type that are always generated to insure that factories will always have Energy for production runs. This isn't a big deal, and I'm OK with approving it now and fixing it later. I mention it in case you want to have a quick look at it while investigating the more important comments below.
> 
>     2. In both LTheory and LTheoryRedux, pressing the "H" key to accelerate time causes a crash:
> 
> 
> ./script/States\Application.lua:181: attempt to perform arithmetic on local 'timeScale' (a nil value)
> 
>     3. When in Flight mode, press Esc to bring up the game control dialog, then click on "Load Game". The seed selection screen pops up briefly but gets replaced by the game control dialog. If you then click on "Return to Game" in the game control dialog, the Seed selection dialog is displayed.
> 
>     4. One very minor thing: I've noticed that when you add a single quote mark in a line of code (usually in a comment), it seems to be adding it as a special character followed by a slanted ("smart") single quote, rather than as the default "straight" single quote character. It's not hurting any of the code, but it is a bit outside the minimal coding standards for the game code. (I know you've asked about coding standards; please consider "straight single-quote characters only" one of those standards. :D )
> 
> 
> Overall, this is now _very_ close to being ready for full approval.

should be good now!
can u direct me to a line where 4 applies?

**Comment by Flatfingers** [comment]
Almost there! With the last change to station placement, LTheoryRedux and LTheory both work, but TestEcon hangs. It looks like the problem might be the loop that finds an acceptable location -- maybe it needs a guard value which, if exceeded, backs off on the allowable distance (or just accepts the last suggested distance, and we deal with "perfecting" this later).

```
script.GameObjects\Entities\Zone.lua
    37  | function Zone:getRandomPos (rng)
--> 38  |   return self.pos + rng:getDir3():scale((0.1 * self.extent) * rng:getExp() ^ rng:getExp())
    39  | end
```

Regarding the odd "smart" single quote, 2 examples in InitFiles.lua:

171:     -- this is dirty for now, but itÂ´s the only category without anything we need to save
187:       -- donÂ´t allow any other than string, boolean and numbers also ignore "current" variables

I'm ready to approve once the TestEcon loop issue is fixed.

**Review by Flatfingers — APPROVED** [review]

**Comment by Flatfingers** [comment]
Nice work!

**Pull request merged**
