### PR TITLE
Get everything working on Ubuntu out of the box, update the README.

### PR DESCRIPTION
**Pull request by dgavedissian**

### CODE REVIEW

**Comment by SeanScherer** [comment]
Hey, I'm on a vanilla / fresh install of Kubuntu 22.04, and followed the instructions from the  (modified) readme.

On the step " python configure.py", I get the following error message:


```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/seancj/Coding/LimitTheoryUbuntu/ltheory/build/CMakeFiles/CMakeOutput.log".
See also "/home/seancj/Coding/LimitTheoryUbuntu/ltheory/build/CMakeFiles/CMakeError.log".
```

An easy fix I bet, but still worth the fix I reckoned :) .

**Comment by dgavedissian** [comment]
Ah thank you, looks like I missed `build-essential` in the list of dependencies. If you install that, you should be good 👍

**Comment by SeanScherer** [comment]
'nother minor thing: For me, "apt install" errored out due to "python".
If you do that as a separate command, then the rest of the stuff would get installed, and user could then proceed to install python-is-python3 as/if required.

**Comment by dgavedissian** [comment]
Ah, is `python3` the right package on Ubuntu 22.04? If so, I'll change it to that.

**Comment by SeanScherer** [comment]
For outside onlookers - with the recent commits, this now built on my vanilla Kubuntu 22.04 :) .

**Review by nikodemak — APPROVED** [review]

**Pull request merged**
