### PR TITLE
Render build version & adjust WIP text

### PR DESCRIPTION
**Pull request by IllustrisJack**
- Changes the kinda aggressive sounding `EXPERIMENTAL BUILD - NOT FINAL!` to `WORK IN PROGRESS` :D 
- Renders the build number / game version on the bottom left
- Makes the text a bit transparent
- Changes are for the upcoming nightly release change #180

### CODE REVIEW

**Comment by dgavedissian** [comment]
This is much better, thanks! Could we perhaps put the version number in the bottom right corner somewhere?

**Comment by IllustrisJack** [comment]
> This is much better, thanks! Could we perhaps put the version number in the bottom right corner somewhere?

sure

**Comment by IllustrisJack** [comment]
> This is much better, thanks! Could we perhaps put the version number in the bottom right corner somewhere?

i was just a bit worried about clipping :D

**Review by dgavedissian — APPROVED** [review]
Ship it

**Pull request merged**
